# Generated by Django 6.0.3 on 2026-04-05 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Out for Delivery, Customs Clearance', max_length=100, unique=True)),
                ('marker_color', models.CharField(choices=[('green', 'Green (In Transit)'), ('red', 'Red (Stopped/Issue)'), ('yellow', 'Yellow (Waiting/Pending)'), ('gray', 'Gray (Delivered/Unknown)')], default='gray', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Custom Statuses',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=20, unique=True)),
                ('airway_bill_number', models.CharField(blank=True, help_text='AWB Number', max_length=50, null=True)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_address', models.TextField(blank=True, null=True)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_address', models.TextField(blank=True, null=True)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('current_location_name', models.CharField(default='Origin Sorting Hub', help_text='Type city/country manually.', max_length=100)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('package_content', models.CharField(blank=True, max_length=200, null=True)),
                ('package_description', models.TextField(blank=True, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('origin_lat', models.FloatField(default=40.7128)),
                ('origin_lng', models.FloatField(default=-74.006)),
                ('dest_lat', models.FloatField(default=34.0522)),
                ('dest_lng', models.FloatField(default=-118.2437)),
                ('current_lat', models.FloatField(default=40.7128)),
                ('current_lng', models.FloatField(default=-74.006)),
                ('estimated_delivery', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_update', models.TextField(default='Shipment logged in network.')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courier_app.customstatus')),
            ],
        ),
    ]
