# Generated by Django 6.0.3 on 2026-04-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customstatus',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Custom Statuses'},
        ),
        migrations.AddField(
            model_name='customstatus',
            name='sort_order',
            field=models.IntegerField(default=100, help_text='Chronological order for dropdowns'),
        ),
    ]
