# Generated by Django 6.0.3 on 2026-04-12 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_app', '0003_supportticket_alter_shipment_tracking_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order in chronological sequence if timestamp is identical')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='courier_app.shipment')),
            ],
            options={
                'ordering': ['sort_order', 'timestamp'],
            },
        ),
    ]
