# Generated by Django 6.0.3 on 2026-09-05 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_app', '0004_trackingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
