# Generated by Django 6.0.3 on 2026-09-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_app', '0005_alter_trackingevent_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_diplomatic',
            field=models.BooleanField(default=True, verbose_name='Diplomatic Pouch Security Clearance'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='reference_id',
            field=models.CharField(blank=True, help_text='e.g. DP-CAN-9812-α', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('courier', 'Courier Escort'), ('armored', 'Armored Transport'), ('air', 'Secure Air Transfer'), ('embassy', 'Embassy / High Commission')], default='courier', max_length=50),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='verification_badge',
            field=models.CharField(blank=True, help_text='e.g. VERIFIED: COURIER SECTION', max_length=100, null=True),
        ),
    ]
