# Generated by Django 6.0.3 on 2026-10-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_app', '0006_shipment_is_diplomatic_shipment_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='courier_phone',
            field=models.CharField(blank=True, help_text='e.g. +1 (800) 555-TRANSGLO or Courier Hotline', max_length=50, null=True, verbose_name='Courier / Dispatch Agent Phone'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='dimensions',
            field=models.CharField(blank=True, default='30 x 20 x 15 cm', max_length=50, null=True, verbose_name='Dimensions (L x W x H)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pieces_count',
            field=models.IntegerField(default=1, verbose_name='Number of Pieces / Pouches'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_phone',
            field=models.CharField(blank=True, help_text='e.g. +44 20 7946 0912', max_length=50, null=True, verbose_name='Receiver Contact Phone'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_phone',
            field=models.CharField(blank=True, help_text='e.g. +1 (555) 019-2834', max_length=50, null=True, verbose_name='Sender Contact Phone'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='service_type',
            field=models.CharField(blank=True, default='Express Air Delivery', help_text='e.g. Express Air Delivery, Diplomatic Courier Escort, Priority International', max_length=100, null=True, verbose_name='Shipping Service Type'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='is_diplomatic',
            field=models.BooleanField(default=False, verbose_name='Diplomatic Pouch Security Clearance'),
        ),
    ]
